import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// [id, name, symbol, atomicMass, category, period, groupNumber|null, state, isRadioactive, isSynthetic]
type Row = [number, string, string, number, string, number, number | null, string, boolean, boolean]

const elements: Row[] = [
  [1,   'Hydrogen',      'H',  1.008,   'nonmetal',        1, 1,    'gas',       false, false],
  [2,   'Helium',        'He', 4.003,   'noble_gas',       1, 18,   'gas',       false, false],
  [3,   'Lithium',       'Li', 6.941,   'alkali_metal',    2, 1,    'solid',     false, false],
  [4,   'Beryllium',     'Be', 9.012,   'alkaline_earth',  2, 2,    'solid',     false, false],
  [5,   'Boron',         'B',  10.811,  'metalloid',       2, 13,   'solid',     false, false],
  [6,   'Carbon',        'C',  12.011,  'nonmetal',        2, 14,   'solid',     false, false],
  [7,   'Nitrogen',      'N',  14.007,  'nonmetal',        2, 15,   'gas',       false, false],
  [8,   'Oxygen',        'O',  15.999,  'nonmetal',        2, 16,   'gas',       false, false],
  [9,   'Fluorine',      'F',  18.998,  'halogen',         2, 17,   'gas',       false, false],
  [10,  'Neon',          'Ne', 20.180,  'noble_gas',       2, 18,   'gas',       false, false],
  [11,  'Sodium',        'Na', 22.990,  'alkali_metal',    3, 1,    'solid',     false, false],
  [12,  'Magnesium',     'Mg', 24.305,  'alkaline_earth',  3, 2,    'solid',     false, false],
  [13,  'Aluminum',      'Al', 26.982,  'post_transition', 3, 13,   'solid',     false, false],
  [14,  'Silicon',       'Si', 28.086,  'metalloid',       3, 14,   'solid',     false, false],
  [15,  'Phosphorus',    'P',  30.974,  'nonmetal',        3, 15,   'solid',     false, false],
  [16,  'Sulfur',        'S',  32.065,  'nonmetal',        3, 16,   'solid',     false, false],
  [17,  'Chlorine',      'Cl', 35.453,  'halogen',         3, 17,   'gas',       false, false],
  [18,  'Argon',         'Ar', 39.948,  'noble_gas',       3, 18,   'gas',       false, false],
  [19,  'Potassium',     'K',  39.098,  'alkali_metal',    4, 1,    'solid',     false, false],
  [20,  'Calcium',       'Ca', 40.078,  'alkaline_earth',  4, 2,    'solid',     false, false],
  [21,  'Scandium',      'Sc', 44.956,  'transition_metal',4, 3,    'solid',     false, false],
  [22,  'Titanium',      'Ti', 47.867,  'transition_metal',4, 4,    'solid',     false, false],
  [23,  'Vanadium',      'V',  50.942,  'transition_metal',4, 5,    'solid',     false, false],
  [24,  'Chromium',      'Cr', 51.996,  'transition_metal',4, 6,    'solid',     false, false],
  [25,  'Manganese',     'Mn', 54.938,  'transition_metal',4, 7,    'solid',     false, false],
  [26,  'Iron',          'Fe', 55.845,  'transition_metal',4, 8,    'solid',     false, false],
  [27,  'Cobalt',        'Co', 58.933,  'transition_metal',4, 9,    'solid',     false, false],
  [28,  'Nickel',        'Ni', 58.693,  'transition_metal',4, 10,   'solid',     false, false],
  [29,  'Copper',        'Cu', 63.546,  'transition_metal',4, 11,   'solid',     false, false],
  [30,  'Zinc',          'Zn', 65.380,  'transition_metal',4, 12,   'solid',     false, false],
  [31,  'Gallium',       'Ga', 69.723,  'post_transition', 4, 13,   'solid',     false, false],
  [32,  'Germanium',     'Ge', 72.630,  'metalloid',       4, 14,   'solid',     false, false],
  [33,  'Arsenic',       'As', 74.922,  'metalloid',       4, 15,   'solid',     false, false],
  [34,  'Selenium',      'Se', 78.971,  'nonmetal',        4, 16,   'solid',     false, false],
  [35,  'Bromine',       'Br', 79.904,  'halogen',         4, 17,   'liquid',    false, false],
  [36,  'Krypton',       'Kr', 83.798,  'noble_gas',       4, 18,   'gas',       false, false],
  [37,  'Rubidium',      'Rb', 85.468,  'alkali_metal',    5, 1,    'solid',     false, false],
  [38,  'Strontium',     'Sr', 87.620,  'alkaline_earth',  5, 2,    'solid',     false, false],
  [39,  'Yttrium',       'Y',  88.906,  'transition_metal',5, 3,    'solid',     false, false],
  [40,  'Zirconium',     'Zr', 91.224,  'transition_metal',5, 4,    'solid',     false, false],
  [41,  'Niobium',       'Nb', 92.906,  'transition_metal',5, 5,    'solid',     false, false],
  [42,  'Molybdenum',    'Mo', 95.960,  'transition_metal',5, 6,    'solid',     false, false],
  [43,  'Technetium',    'Tc', 98.000,  'transition_metal',5, 7,    'solid',     true,  true ],
  [44,  'Ruthenium',     'Ru', 101.070, 'transition_metal',5, 8,    'solid',     false, false],
  [45,  'Rhodium',       'Rh', 102.906, 'transition_metal',5, 9,    'solid',     false, false],
  [46,  'Palladium',     'Pd', 106.420, 'transition_metal',5, 10,   'solid',     false, false],
  [47,  'Silver',        'Ag', 107.868, 'transition_metal',5, 11,   'solid',     false, false],
  [48,  'Cadmium',       'Cd', 112.411, 'transition_metal',5, 12,   'solid',     false, false],
  [49,  'Indium',        'In', 114.818, 'post_transition', 5, 13,   'solid',     false, false],
  [50,  'Tin',           'Sn', 118.710, 'post_transition', 5, 14,   'solid',     false, false],
  [51,  'Antimony',      'Sb', 121.760, 'metalloid',       5, 15,   'solid',     false, false],
  [52,  'Tellurium',     'Te', 127.600, 'metalloid',       5, 16,   'solid',     false, false],
  [53,  'Iodine',        'I',  126.904, 'halogen',         5, 17,   'solid',     false, false],
  [54,  'Xenon',         'Xe', 131.293, 'noble_gas',       5, 18,   'gas',       false, false],
  [55,  'Cesium',        'Cs', 132.905, 'alkali_metal',    6, 1,    'solid',     false, false],
  [56,  'Barium',        'Ba', 137.327, 'alkaline_earth',  6, 2,    'solid',     false, false],
  [57,  'Lanthanum',     'La', 138.905, 'lanthanide',      6, null,  'solid',    false, false],
  [58,  'Cerium',        'Ce', 140.116, 'lanthanide',      6, null,  'solid',    false, false],
  [59,  'Praseodymium',  'Pr', 140.908, 'lanthanide',      6, null,  'solid',    false, false],
  [60,  'Neodymium',     'Nd', 144.242, 'lanthanide',      6, null,  'solid',    false, false],
  [61,  'Promethium',    'Pm', 145.000, 'lanthanide',      6, null,  'solid',    true,  true ],
  [62,  'Samarium',      'Sm', 150.360, 'lanthanide',      6, null,  'solid',    false, false],
  [63,  'Europium',      'Eu', 151.964, 'lanthanide',      6, null,  'solid',    false, false],
  [64,  'Gadolinium',    'Gd', 157.250, 'lanthanide',      6, null,  'solid',    false, false],
  [65,  'Terbium',       'Tb', 158.925, 'lanthanide',      6, null,  'solid',    false, false],
  [66,  'Dysprosium',    'Dy', 162.500, 'lanthanide',      6, null,  'solid',    false, false],
  [67,  'Holmium',       'Ho', 164.930, 'lanthanide',      6, null,  'solid',    false, false],
  [68,  'Erbium',        'Er', 167.259, 'lanthanide',      6, null,  'solid',    false, false],
  [69,  'Thulium',       'Tm', 168.934, 'lanthanide',      6, null,  'solid',    false, false],
  [70,  'Ytterbium',     'Yb', 173.045, 'lanthanide',      6, null,  'solid',    false, false],
  [71,  'Lutetium',      'Lu', 174.967, 'lanthanide',      6, null,  'solid',    false, false],
  [72,  'Hafnium',       'Hf', 178.490, 'transition_metal',6, 4,    'solid',     false, false],
  [73,  'Tantalum',      'Ta', 180.948, 'transition_metal',6, 5,    'solid',     false, false],
  [74,  'Tungsten',      'W',  183.840, 'transition_metal',6, 6,    'solid',     false, false],
  [75,  'Rhenium',       'Re', 186.207, 'transition_metal',6, 7,    'solid',     false, false],
  [76,  'Osmium',        'Os', 190.230, 'transition_metal',6, 8,    'solid',     false, false],
  [77,  'Iridium',       'Ir', 192.217, 'transition_metal',6, 9,    'solid',     false, false],
  [78,  'Platinum',      'Pt', 195.084, 'transition_metal',6, 10,   'solid',     false, false],
  [79,  'Gold',          'Au', 196.967, 'transition_metal',6, 11,   'solid',     false, false],
  [80,  'Mercury',       'Hg', 200.592, 'transition_metal',6, 12,   'liquid',    false, false],
  [81,  'Thallium',      'Tl', 204.383, 'post_transition', 6, 13,   'solid',     false, false],
  [82,  'Lead',          'Pb', 207.200, 'post_transition', 6, 14,   'solid',     false, false],
  [83,  'Bismuth',       'Bi', 208.980, 'post_transition', 6, 15,   'solid',     false, false],
  [84,  'Polonium',      'Po', 209.000, 'metalloid',       6, 16,   'solid',     true,  false],
  [85,  'Astatine',      'At', 210.000, 'halogen',         6, 17,   'solid',     true,  false],
  [86,  'Radon',         'Rn', 222.000, 'noble_gas',       6, 18,   'gas',       true,  false],
  [87,  'Francium',      'Fr', 223.000, 'alkali_metal',    7, 1,    'solid',     true,  false],
  [88,  'Radium',        'Ra', 226.000, 'alkaline_earth',  7, 2,    'solid',     true,  false],
  [89,  'Actinium',      'Ac', 227.000, 'actinide',        7, null,  'solid',    true,  false],
  [90,  'Thorium',       'Th', 232.038, 'actinide',        7, null,  'solid',    true,  false],
  [91,  'Protactinium',  'Pa', 231.036, 'actinide',        7, null,  'solid',    true,  false],
  [92,  'Uranium',       'U',  238.029, 'actinide',        7, null,  'solid',    true,  false],
  [93,  'Neptunium',     'Np', 237.000, 'actinide',        7, null,  'solid',    true,  true ],
  [94,  'Plutonium',     'Pu', 244.000, 'actinide',        7, null,  'solid',    true,  true ],
  [95,  'Americium',     'Am', 243.000, 'actinide',        7, null,  'solid',    true,  true ],
  [96,  'Curium',        'Cm', 247.000, 'actinide',        7, null,  'solid',    true,  true ],
  [97,  'Berkelium',     'Bk', 247.000, 'actinide',        7, null,  'solid',    true,  true ],
  [98,  'Californium',   'Cf', 251.000, 'actinide',        7, null,  'solid',    true,  true ],
  [99,  'Einsteinium',   'Es', 252.000, 'actinide',        7, null,  'solid',    true,  true ],
  [100, 'Fermium',       'Fm', 257.000, 'actinide',        7, null,  'solid',    true,  true ],
  [101, 'Mendelevium',   'Md', 258.000, 'actinide',        7, null,  'solid',    true,  true ],
  [102, 'Nobelium',      'No', 259.000, 'actinide',        7, null,  'solid',    true,  true ],
  [103, 'Lawrencium',    'Lr', 266.000, 'actinide',        7, null,  'solid',    true,  true ],
  [104, 'Rutherfordium', 'Rf', 267.000, 'transition_metal',7, 4,    'synthetic', true,  true ],
  [105, 'Dubnium',       'Db', 268.000, 'transition_metal',7, 5,    'synthetic', true,  true ],
  [106, 'Seaborgium',    'Sg', 269.000, 'transition_metal',7, 6,    'synthetic', true,  true ],
  [107, 'Bohrium',       'Bh', 270.000, 'transition_metal',7, 7,    'synthetic', true,  true ],
  [108, 'Hassium',       'Hs', 277.000, 'transition_metal',7, 8,    'synthetic', true,  true ],
  [109, 'Meitnerium',    'Mt', 278.000, 'transition_metal',7, 9,    'synthetic', true,  true ],
  [110, 'Darmstadtium',  'Ds', 281.000, 'transition_metal',7, 10,   'synthetic', true,  true ],
  [111, 'Roentgenium',   'Rg', 282.000, 'transition_metal',7, 11,   'synthetic', true,  true ],
  [112, 'Copernicium',   'Cn', 285.000, 'transition_metal',7, 12,   'synthetic', true,  true ],
  [113, 'Nihonium',      'Nh', 286.000, 'post_transition', 7, 13,   'synthetic', true,  true ],
  [114, 'Flerovium',     'Fl', 289.000, 'post_transition', 7, 14,   'synthetic', true,  true ],
  [115, 'Moscovium',     'Mc', 290.000, 'post_transition', 7, 15,   'synthetic', true,  true ],
  [116, 'Livermorium',   'Lv', 293.000, 'post_transition', 7, 16,   'synthetic', true,  true ],
  [117, 'Tennessine',    'Ts', 294.000, 'halogen',         7, 17,   'synthetic', true,  true ],
  [118, 'Oganesson',     'Og', 294.000, 'noble_gas',       7, 18,   'synthetic', true,  true ],
]

async function main() {
  console.log('Seeding elements...')
  for (const [id, name, symbol, atomicMass, category, period, groupNumber, stateAtRoomTemp, isRadioactive, isSynthetic] of elements) {
    await prisma.element.upsert({
      where: { id },
      update: {},
      create: { id, name, symbol, atomicNumber: id, atomicMass, category, period, groupNumber, stateAtRoomTemp, isRadioactive, isSynthetic },
    })
  }
  console.log(`Done — ${elements.length} elements seeded`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
